require("prototypes/cables")
require("prototypes/silica-recipe")
require("prototypes/silicon-recipe")
require("prototypes/optical-fiber")
require("prototypes/gyro")
require("prototypes/razorgrass")
require("prototypes/stone")
require("prototypes/basic-crusher")
require("recipes/silica-matter")

